"""Enumerations for the deterministic rules layer.

Decisions are represented by explicit enums and stable string reason codes, never by
ad-hoc strings, so tests and analytics can rely on them.
"""

from __future__ import annotations

from enum import StrEnum


class DecisionOutcome(StrEnum):
    eligible = "eligible"
    ineligible = "ineligible"
    needs_information = "needs_information"
    requires_review = "requires_review"
    requires_approval = "requires_approval"
    escalate = "escalate"
    blocked = "blocked"


class RiskLevel(StrEnum):
    read_only = "read_only"
    low = "low"
    medium = "medium"
    high = "high"
    blocked = "blocked"


class Route(StrEnum):
    continue_processing = "continue_processing"
    await_agent = "await_agent"
    await_supervisor = "await_supervisor"
    needs_information = "needs_information"
    escalate = "escalate"
    manual_handling = "manual_handling"
    blocked = "blocked"


class ApprovalRole(StrEnum):
    none = "none"
    agent = "agent"
    supervisor = "supervisor"


class ActionType(StrEnum):
    """Consequential action a workflow might later propose. Drives risk and routing."""

    information = "information"
    ticket_status_update = "ticket_status_update"
    return_rma = "return_rma"
    replacement = "replacement"
    refund = "refund"
    cancellation = "cancellation"


class ReturnReason(StrEnum):
    changed_mind = "changed_mind"
    damaged = "damaged"
    incorrect_item = "incorrect_item"
    not_as_described = "not_as_described"
    other = "other"


class ItemCondition(StrEnum):
    unused = "unused"
    opened = "opened"
    used = "used"
    damaged = "damaged"
    unknown = "unknown"


class RefundBasis(StrEnum):
    """The justification a refund relies on."""

    returned_item = "returned_item"
    damaged_item = "damaged_item"
    incorrect_item = "incorrect_item"
    approved_missing_delivery = "approved_missing_delivery"
    unsupported = "unsupported"


class ReasonCode(StrEnum):
    # --- Ownership ---
    CUSTOMER_NOT_IDENTIFIED = "CUSTOMER_NOT_IDENTIFIED"
    CUSTOMER_MATCH_AMBIGUOUS = "CUSTOMER_MATCH_AMBIGUOUS"
    ORDER_NOT_IDENTIFIED = "ORDER_NOT_IDENTIFIED"
    ORDER_MATCH_AMBIGUOUS = "ORDER_MATCH_AMBIGUOUS"
    ORDER_OWNERSHIP_CONFIRMED = "ORDER_OWNERSHIP_CONFIRMED"
    ORDER_OWNERSHIP_MISMATCH = "ORDER_OWNERSHIP_MISMATCH"
    CROSS_CUSTOMER_ACCESS_BLOCKED = "CROSS_CUSTOMER_ACCESS_BLOCKED"

    # --- Returns ---
    RETURN_WITHIN_WINDOW = "RETURN_WITHIN_WINDOW"
    RETURN_WINDOW_EXPIRED = "RETURN_WINDOW_EXPIRED"
    RETURN_NOT_YET_APPLICABLE = "RETURN_NOT_YET_APPLICABLE"
    ITEM_ALREADY_RETURNED = "ITEM_ALREADY_RETURNED"
    ITEM_CONDITION_NOT_ELIGIBLE = "ITEM_CONDITION_NOT_ELIGIBLE"
    DAMAGED_ITEM_EXCEPTION = "DAMAGED_ITEM_EXCEPTION"
    INCORRECT_ITEM_EXCEPTION = "INCORRECT_ITEM_EXCEPTION"
    DELIVERY_DATE_MISSING = "DELIVERY_DATE_MISSING"

    # --- Refunds ---
    REFUND_ELIGIBLE = "REFUND_ELIGIBLE"
    REFUND_REASON_UNSUPPORTED = "REFUND_REASON_UNSUPPORTED"
    REFUND_AMOUNT_INVALID = "REFUND_AMOUNT_INVALID"
    REFUND_EXCEEDS_ITEM_TOTAL = "REFUND_EXCEEDS_ITEM_TOTAL"
    REFUND_EXCEEDS_REMAINING_ORDER_BALANCE = "REFUND_EXCEEDS_REMAINING_ORDER_BALANCE"
    RETURN_NOT_RECEIVED = "RETURN_NOT_RECEIVED"
    REFUND_SUPERVISOR_APPROVAL_REQUIRED = "REFUND_SUPERVISOR_APPROVAL_REQUIRED"
    REFUND_MEDIUM_RISK = "REFUND_MEDIUM_RISK"
    REFUND_HIGH_RISK = "REFUND_HIGH_RISK"
    REFUND_OVER_SYSTEM_LIMIT = "REFUND_OVER_SYSTEM_LIMIT"
    REFUND_BLOCKED = "REFUND_BLOCKED"

    # --- Cancellations ---
    CANCELLATION_ELIGIBLE = "CANCELLATION_ELIGIBLE"
    ORDER_ALREADY_CANCELLED = "ORDER_ALREADY_CANCELLED"
    ORDER_ALREADY_SHIPPED = "ORDER_ALREADY_SHIPPED"
    ORDER_ALREADY_DELIVERED = "ORDER_ALREADY_DELIVERED"
    ORDER_STATUS_NOT_CANCELLABLE = "ORDER_STATUS_NOT_CANCELLABLE"
    RETURN_FLOW_RECOMMENDED = "RETURN_FLOW_RECOMMENDED"
    CANCELLATION_SUPERVISOR_APPROVAL_REQUIRED = (
        "CANCELLATION_SUPERVISOR_APPROVAL_REQUIRED"
    )
    SHIPMENT_ASSUMED_ABSENT = "SHIPMENT_ASSUMED_ABSENT"

    # --- Delivery delay ---
    DELIVERY_ON_TIME = "DELIVERY_ON_TIME"
    DELIVERY_MINOR_DELAY = "DELIVERY_MINOR_DELAY"
    DELIVERY_SIGNIFICANT_DELAY = "DELIVERY_SIGNIFICANT_DELAY"
    DELIVERY_SEVERE_DELAY = "DELIVERY_SEVERE_DELAY"
    SHIPMENT_EXCEPTION = "SHIPMENT_EXCEPTION"
    SHIPMENT_REPORTED_LOST = "SHIPMENT_REPORTED_LOST"
    ORDER_NOT_SHIPPED = "ORDER_NOT_SHIPPED"
    DELIVERY_ALREADY_COMPLETED = "DELIVERY_ALREADY_COMPLETED"

    # --- Missing delivery ---
    DELIVERED_BUT_DISPUTED = "DELIVERED_BUT_DISPUTED"
    MISSING_DELIVERY_ESCALATION_REQUIRED = "MISSING_DELIVERY_ESCALATION_REQUIRED"
    SHIPMENT_CONFIRMED_LOST = "SHIPMENT_CONFIRMED_LOST"
    LOST_SHIPMENT_REMEDY_ELIGIBLE = "LOST_SHIPMENT_REMEDY_ELIGIBLE"
    SHIPMENT_STILL_IN_TRANSIT = "SHIPMENT_STILL_IN_TRANSIT"
    SHIPMENT_EXCEPTION_REQUIRES_REVIEW = "SHIPMENT_EXCEPTION_REQUIRES_REVIEW"
    SHIPMENT_DATA_MISSING = "SHIPMENT_DATA_MISSING"

    # --- Remedies (damaged / incorrect) ---
    DAMAGED_ITEM_REMEDY_ELIGIBLE = "DAMAGED_ITEM_REMEDY_ELIGIBLE"
    DAMAGED_ITEM_REPORT_OUTSIDE_WINDOW = "DAMAGED_ITEM_REPORT_OUTSIDE_WINDOW"
    DAMAGE_EVIDENCE_INSUFFICIENT = "DAMAGE_EVIDENCE_INSUFFICIENT"
    INCORRECT_ITEM_REMEDY_ELIGIBLE = "INCORRECT_ITEM_REMEDY_ELIGIBLE"
    RECEIVED_SKU_MATCHES_ORDER = "RECEIVED_SKU_MATCHES_ORDER"
    RECEIVED_SKU_UNKNOWN = "RECEIVED_SKU_UNKNOWN"
    ITEM_MISMATCH_UNVERIFIED = "ITEM_MISMATCH_UNVERIFIED"
    REPLACEMENT_SUPERVISOR_APPROVAL_REQUIRED = (
        "REPLACEMENT_SUPERVISOR_APPROVAL_REQUIRED"
    )

    # --- Policy validity ---
    POLICY_ACTIVE = "POLICY_ACTIVE"
    POLICY_NOT_FOUND = "POLICY_NOT_FOUND"
    POLICY_NOT_EFFECTIVE_YET = "POLICY_NOT_EFFECTIVE_YET"
    POLICY_EXPIRED = "POLICY_EXPIRED"
    POLICY_SUPERSEDED = "POLICY_SUPERSEDED"
    POLICY_CONFLICT = "POLICY_CONFLICT"
    POLICY_CANNOT_AUTHORISE_ACTION = "POLICY_CANNOT_AUTHORISE_ACTION"

    # --- Routing ---
    CONFIDENCE_SUFFICIENT = "CONFIDENCE_SUFFICIENT"
    CONFIDENCE_AGENT_REVIEW = "CONFIDENCE_AGENT_REVIEW"
    CONFIDENCE_TOO_LOW = "CONFIDENCE_TOO_LOW"
    INJECTION_FORCED_ESCALATION = "INJECTION_FORCED_ESCALATION"
    MULTIPLE_CUSTOMER_MATCHES = "MULTIPLE_CUSTOMER_MATCHES"
    MULTIPLE_ORDER_MATCHES = "MULTIPLE_ORDER_MATCHES"
    UNKNOWN_CATEGORY_ESCALATION = "UNKNOWN_CATEGORY_ESCALATION"
    NO_SUPPORTING_POLICY = "NO_SUPPORTING_POLICY"
    DEPENDENCY_FAILURE_ESCALATION = "DEPENDENCY_FAILURE_ESCALATION"
    SUPERVISOR_APPROVAL_REQUIRED = "SUPERVISOR_APPROVAL_REQUIRED"
    AGENT_REVIEW_REQUIRED = "AGENT_REVIEW_REQUIRED"
    NO_APPROVAL_REQUIRED = "NO_APPROVAL_REQUIRED"
    ACTION_MAY_PROCEED = "ACTION_MAY_PROCEED"
    DUPLICATE_CHECK_REQUIRED = "DUPLICATE_CHECK_REQUIRED"
