"""s1 domain model

Revision ID: defd09b8380e
Revises: 0001_enable_pgvector
Create Date: 2026-07-16 03:19:33.421305

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "defd09b8380e"
down_revision: str | None = "0001_enable_pgvector"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("external_reference", sa.String(length=40), nullable=False),
        sa.Column("first_name", sa.String(length=80), nullable=False),
        sa.Column("last_name", sa.String(length=80), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=False),
        sa.Column(
            "tier", sa.Enum("standard", "vip", name="customer_tier"), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
        sa.UniqueConstraint("email", name=op.f("uq_customers_email")),
        sa.UniqueConstraint(
            "external_reference", name=op.f("uq_customers_external_reference")
        ),
    )
    op.create_index(
        "ix_customers_last_first",
        "customers",
        ["last_name", "first_name"],
        unique=False,
    )
    op.create_table(
        "policies",
        sa.Column("topic", sa.String(length=60), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policies")),
        sa.UniqueConstraint("topic", "title", name="uq_policies_topic_title"),
    )
    op.create_index("ix_policies_topic", "policies", ["topic"], unique=False)
    op.create_table(
        "products",
        sa.Column("sku", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "kitchenware",
                "home_decor",
                "bedding_and_towels",
                "small_furniture",
                "consumer_accessories",
                name="product_category",
            ),
            nullable=False,
        ),
        sa.Column("unit_price_pence", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "unit_price_pence > 0", name=op.f("ck_products_unit_price_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("sku", name=op.f("uq_products_sku")),
    )
    op.create_index("ix_products_category", "products", ["category"], unique=False)
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column(
            "role",
            sa.Enum("support_agent", "supervisor", name="user_role"),
            nullable=False,
        ),
        sa.Column("hashed_password", sa.String(length=128), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "orders",
        sa.Column("order_number", sa.String(length=32), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "placed",
                "paid",
                "processing",
                "shipped",
                "delivered",
                "cancelled",
                "partially_refunded",
                "refunded",
                name="order_status",
            ),
            nullable=False,
        ),
        sa.Column("subtotal_pence", sa.Integer(), nullable=False),
        sa.Column("delivery_fee_pence", sa.Integer(), nullable=False),
        sa.Column("discount_pence", sa.Integer(), nullable=False),
        sa.Column("total_paid_pence", sa.Integer(), nullable=False),
        sa.Column("placed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "delivery_fee_pence >= 0", name=op.f("ck_orders_delivery_fee_non_negative")
        ),
        sa.CheckConstraint(
            "discount_pence >= 0", name=op.f("ck_orders_discount_non_negative")
        ),
        sa.CheckConstraint(
            "subtotal_pence >= 0", name=op.f("ck_orders_subtotal_non_negative")
        ),
        sa.CheckConstraint(
            "total_paid_pence = subtotal_pence + delivery_fee_pence - discount_pence",
            name=op.f("ck_orders_total_paid_consistent"),
        ),
        sa.CheckConstraint(
            "total_paid_pence >= 0", name=op.f("ck_orders_total_paid_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_orders_customer_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("order_number", name=op.f("uq_orders_order_number")),
    )
    op.create_index("ix_orders_customer_id", "orders", ["customer_id"], unique=False)
    op.create_index("ix_orders_placed_at", "orders", ["placed_at"], unique=False)
    op.create_index("ix_orders_status", "orders", ["status"], unique=False)
    op.create_table(
        "policy_versions",
        sa.Column("policy_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "active", "superseded", "expired", name="policy_status"),
            nullable=False,
        ),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to > effective_from",
            name=op.f("ck_policy_versions_effective_range_valid"),
        ),
        sa.CheckConstraint(
            "version >= 1", name=op.f("ck_policy_versions_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["policies.id"],
            name=op.f("fk_policy_versions_policy_id_policies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_versions")),
        sa.UniqueConstraint(
            "policy_id", "version", name="uq_policy_versions_policy_version"
        ),
    )
    op.create_index(
        "ix_policy_versions_effective_from",
        "policy_versions",
        ["effective_from"],
        unique=False,
    )
    op.create_index(
        "ix_policy_versions_status", "policy_versions", ["status"], unique=False
    )
    op.create_table(
        "order_items",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price_pence", sa.Integer(), nullable=False),
        sa.Column("line_total_pence", sa.Integer(), nullable=False),
        sa.Column("is_returned", sa.Boolean(), nullable=False),
        sa.Column("returned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "line_total_pence = quantity * unit_price_pence",
            name=op.f("ck_order_items_line_total_consistent"),
        ),
        sa.CheckConstraint(
            "line_total_pence >= 0", name=op.f("ck_order_items_line_total_non_negative")
        ),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_order_items_quantity_positive")
        ),
        sa.CheckConstraint(
            "unit_price_pence >= 0",
            name=op.f("ck_order_items_item_unit_price_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_items_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_order_items_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_items")),
        sa.UniqueConstraint(
            "order_id", "product_id", name="uq_order_items_order_product"
        ),
    )
    op.create_index(
        "ix_order_items_order_id", "order_items", ["order_id"], unique=False
    )
    op.create_table(
        "shipments",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("carrier", sa.String(length=60), nullable=False),
        sa.Column("tracking_number", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "label_created",
                "in_transit",
                "out_for_delivery",
                "delivered",
                "exception",
                "lost",
                name="shipment_status",
            ),
            nullable=False,
        ),
        sa.Column("promised_delivery_date", sa.Date(), nullable=False),
        sa.Column("shipped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'delivered' OR delivered_at IS NOT NULL",
            name=op.f("ck_shipments_delivered_requires_date"),
        ),
        sa.CheckConstraint(
            "status = 'delivered' OR delivered_at IS NULL",
            name=op.f("ck_shipments_undelivered_has_no_date"),
        ),
        sa.CheckConstraint(
            "delivered_at IS NULL OR shipped_at IS NULL OR delivered_at >= shipped_at",
            name=op.f("ck_shipments_delivered_after_shipped"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_shipments_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipments")),
        sa.UniqueConstraint("order_id", name=op.f("uq_shipments_order_id")),
        sa.UniqueConstraint(
            "tracking_number", name=op.f("uq_shipments_tracking_number")
        ),
    )
    op.create_index("ix_shipments_status", "shipments", ["status"], unique=False)
    op.create_table(
        "tickets",
        sa.Column("ticket_reference", sa.String(length=32), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=True),
        sa.Column("order_id", sa.UUID(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "order_tracking",
                "delayed_delivery",
                "missing_delivery",
                "damaged_item",
                "incorrect_item",
                "return_request",
                "refund_request",
                "cancellation_request",
                "product_policy_question",
                "unknown",
                name="ticket_category",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "received",
                "processing",
                "awaiting_agent",
                "awaiting_approval",
                "escalated",
                "needs_information",
                "resolved",
                "failed",
                "closed",
                name="ticket_status",
            ),
            nullable=False,
        ),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("classification_confidence", sa.Float(), nullable=True),
        sa.Column("injection_flag", sa.Boolean(), nullable=False),
        sa.Column(
            "priority",
            sa.Enum("low", "normal", "high", "urgent", name="ticket_priority"),
            nullable=False,
        ),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("seed_tag", sa.String(length=60), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "classification_confidence IS NULL OR (classification_confidence >= 0 AND classification_confidence <= 1)",
            name=op.f("ck_tickets_confidence_between_0_and_1"),
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_tickets_customer_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_tickets_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tickets")),
        sa.UniqueConstraint(
            "ticket_reference", name=op.f("uq_tickets_ticket_reference")
        ),
    )
    op.create_index("ix_tickets_category", "tickets", ["category"], unique=False)
    op.create_index("ix_tickets_customer_id", "tickets", ["customer_id"], unique=False)
    op.create_index("ix_tickets_order_id", "tickets", ["order_id"], unique=False)
    op.create_index("ix_tickets_received_at", "tickets", ["received_at"], unique=False)
    op.create_index("ix_tickets_seed_tag", "tickets", ["seed_tag"], unique=False)
    op.create_index("ix_tickets_status", "tickets", ["status"], unique=False)
    op.create_table(
        "ticket_messages",
        sa.Column("ticket_id", sa.UUID(), nullable=False),
        sa.Column(
            "sender",
            sa.Enum("customer", "agent", "supervisor", "system", name="message_sender"),
            nullable=False,
        ),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("is_trusted", sa.Boolean(), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "length(btrim(body)) > 0", name=op.f("ck_ticket_messages_body_not_empty")
        ),
        sa.CheckConstraint(
            "sequence_number >= 1",
            name=op.f("ck_ticket_messages_sequence_number_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
            name=op.f("fk_ticket_messages_ticket_id_tickets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ticket_messages")),
        sa.UniqueConstraint(
            "ticket_id", "sequence_number", name="uq_ticket_messages_ticket_sequence"
        ),
    )
    op.create_index(
        "ix_ticket_messages_ticket_id", "ticket_messages", ["ticket_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ticket_messages_ticket_id", table_name="ticket_messages")
    op.drop_table("ticket_messages")
    op.drop_index("ix_tickets_status", table_name="tickets")
    op.drop_index("ix_tickets_seed_tag", table_name="tickets")
    op.drop_index("ix_tickets_received_at", table_name="tickets")
    op.drop_index("ix_tickets_order_id", table_name="tickets")
    op.drop_index("ix_tickets_customer_id", table_name="tickets")
    op.drop_index("ix_tickets_category", table_name="tickets")
    op.drop_table("tickets")
    op.drop_index("ix_shipments_status", table_name="shipments")
    op.drop_table("shipments")
    op.drop_index("ix_order_items_order_id", table_name="order_items")
    op.drop_table("order_items")
    op.drop_index("ix_policy_versions_status", table_name="policy_versions")
    op.drop_index("ix_policy_versions_effective_from", table_name="policy_versions")
    op.drop_table("policy_versions")
    op.drop_index("ix_orders_status", table_name="orders")
    op.drop_index("ix_orders_placed_at", table_name="orders")
    op.drop_index("ix_orders_customer_id", table_name="orders")
    op.drop_table("orders")
    op.drop_table("users")
    op.drop_index("ix_products_category", table_name="products")
    op.drop_table("products")
    op.drop_index("ix_policies_topic", table_name="policies")
    op.drop_table("policies")
    op.drop_index("ix_customers_last_first", table_name="customers")
    op.drop_table("customers")
    # Postgres keeps native enum types after their tables are dropped; remove them so
    # a later re-upgrade can recreate them cleanly.
    for enum_name in (
        "message_sender",
        "ticket_priority",
        "ticket_status",
        "ticket_category",
        "policy_status",
        "shipment_status",
        "order_status",
        "product_category",
        "customer_tier",
        "user_role",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
    # ### end Alembic commands ###
