"""s3 policy retrieval

Revision ID: bc0f537763c1
Revises: defd09b8380e
Create Date: 2026-07-16 15:37:34.518819

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bc0f537763c1"
down_revision: str | None = "defd09b8380e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # add_column with an inline Enum does not auto-create the PG type, so create it here.
    source_type_enum = postgresql.ENUM(
        "official_policy",
        "historical_policy",
        "test_conflict",
        "hostile_fixture",
        "untrusted_external",
        name="policy_source_type",
        create_type=False,
    )
    source_type_enum.create(op.get_bind(), checkfirst=True)
    op.create_table(
        "policy_chunks",
        sa.Column("policy_version_id", sa.UUID(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("section_path", sa.String(length=255), nullable=False),
        sa.Column("heading", sa.String(length=255), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("search_text", sa.Text(), nullable=False),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english', search_text)", persisted=True),
            nullable=False,
        ),
        sa.Column("embedding", Vector(dim=256), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("character_count", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("citation_id", sa.String(length=120), nullable=False),
        sa.Column(
            "metadata_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["policy_version_id"],
            ["policy_versions.id"],
            name=op.f("fk_policy_chunks_policy_version_id_policy_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_chunks")),
        sa.UniqueConstraint("citation_id", name="uq_policy_chunks_citation_id"),
        sa.UniqueConstraint(
            "policy_version_id", "chunk_index", name="uq_policy_chunks_version_index"
        ),
    )
    op.create_index(
        "ix_policy_chunks_embedding",
        "policy_chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        "ix_policy_chunks_search_vector",
        "policy_chunks",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_policy_chunks_version", "policy_chunks", ["policy_version_id"], unique=False
    )
    op.add_column(
        "policy_versions",
        sa.Column(
            "source_type",
            source_type_enum,
            server_default="official_policy",
            nullable=False,
        ),
    )
    op.add_column(
        "policy_versions",
        sa.Column("source_path", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "policy_versions",
        sa.Column("content_hash", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "policy_versions",
        sa.Column(
            "language", sa.String(length=12), server_default="en-GB", nullable=False
        ),
    )
    op.add_column(
        "policy_versions",
        sa.Column(
            "jurisdiction", sa.String(length=12), server_default="UK", nullable=False
        ),
    )
    op.add_column(
        "policy_versions",
        sa.Column(
            "audience", sa.String(length=30), server_default="support", nullable=False
        ),
    )
    op.add_column(
        "policy_versions",
        sa.Column(
            "is_retrieval_enabled", sa.Boolean(), server_default="true", nullable=False
        ),
    )
    op.add_column(
        "policy_versions",
        sa.Column(
            "metadata_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.add_column(
        "policy_versions",
        sa.Column("indexed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "policy_versions",
        sa.Column("embedding_provider", sa.String(length=60), nullable=True),
    )
    op.add_column(
        "policy_versions",
        sa.Column("embedding_model", sa.String(length=120), nullable=True),
    )
    op.add_column(
        "policy_versions", sa.Column("embedding_dim", sa.Integer(), nullable=True)
    )
    op.add_column(
        "policy_versions",
        sa.Column("chunker_version", sa.String(length=30), nullable=True),
    )
    op.add_column(
        "policy_versions",
        sa.Column("index_schema_version", sa.String(length=30), nullable=True),
    )
    op.create_index(
        "ix_policy_versions_source_type",
        "policy_versions",
        ["source_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_policy_versions_source_type", table_name="policy_versions")
    op.drop_column("policy_versions", "index_schema_version")
    op.drop_column("policy_versions", "chunker_version")
    op.drop_column("policy_versions", "embedding_dim")
    op.drop_column("policy_versions", "embedding_model")
    op.drop_column("policy_versions", "embedding_provider")
    op.drop_column("policy_versions", "indexed_at")
    op.drop_column("policy_versions", "metadata_json")
    op.drop_column("policy_versions", "is_retrieval_enabled")
    op.drop_column("policy_versions", "audience")
    op.drop_column("policy_versions", "jurisdiction")
    op.drop_column("policy_versions", "language")
    op.drop_column("policy_versions", "content_hash")
    op.drop_column("policy_versions", "source_path")
    op.drop_column("policy_versions", "source_type")
    op.drop_index("ix_policy_chunks_version", table_name="policy_chunks")
    op.drop_index(
        "ix_policy_chunks_search_vector",
        table_name="policy_chunks",
        postgresql_using="gin",
    )
    op.drop_index(
        "ix_policy_chunks_embedding",
        table_name="policy_chunks",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("policy_chunks")
    # Postgres keeps the enum type after the column is dropped; remove it too.
    op.execute("DROP TYPE IF EXISTS policy_source_type")
    # ### end Alembic commands ###
